// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class OrderStatusHistory
    {
        public Guid Id { get; set; }
        public Guid OrderId { get; set; }
        public int StatusId { get; set; }
        public DateTime Date { get; set; }
        public string Comment { get; set; }

        public virtual Order Order { get; set; }
        public virtual OrderStatus Status { get; set; }
    }
}