// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class ProductPhoto
    {
        public ProductPhoto()
        {
            ProductMainPhotos = new HashSet<ProductMainPhoto>();
            Products = new HashSet<Product>();
        }

        public Guid Guid { get; set; }
        public string LowResPhotoPath { get; set; }
        public string HighResPhotoPath { get; set; }

        public virtual ICollection<ProductMainPhoto> ProductMainPhotos { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}