// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class ProductPhoto
    {
        public Guid Id { get; set; }
        public Guid ProductId { get; set; }
        public string LowResPhotoPath { get; set; }
        public string HighResPhotoPath { get; set; }

        public virtual Product Product { get; set; }
    }
}