// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class Product
    {
        public Product()
        {
            ProductPhotos = new HashSet<ProductPhoto>();
            ProductsToOrders = new HashSet<ProductsToOrder>();
        }

        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public Guid Id { get; set; }
        public Guid? MainPhotoId { get; set; }
        public bool IsActive { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<ProductPhoto> ProductPhotos { get; set; }
        public virtual ICollection<ProductsToOrder> ProductsToOrders { get; set; }
    }
}