// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class Product
    {
        public Product()
        {
            ProductsToOrders = new HashSet<ProductsToOrder>();
            Photos = new HashSet<ProductPhoto>();
        }

        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string LowImagePath { get; set; }
        public string HighImagePath { get; set; }

        public virtual ProductType ProductType { get; set; }
        public virtual ProductMainPhoto ProductMainPhoto { get; set; }
        public virtual ICollection<ProductsToOrder> ProductsToOrders { get; set; }

        public virtual ICollection<ProductPhoto> Photos { get; set; }
    }
}