// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class ProductMainPhoto
    {
        public int ProductId { get; set; }
        public Guid PhotoId { get; set; }

        public virtual ProductPhoto Photo { get; set; }
        public virtual Product Product { get; set; }
    }
}