// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VegoAPI.VegoAPI.Models.DBEntities
{
    public partial class PromoCodeToOrder
    {
        public string PromoCode { get; set; }
        public Guid OrderId { get; set; }

        public virtual PromoCode PromoCodeNavigation { get; set; }
        public virtual Order Order { get; set; }
    }
}